### ISSUE TITLE
Link for data not correct

### ISSUE THREAD

**Issue by Joel-Dahne** [lamastex/working-manuscript-TopologicalDataAnalysisOnABrainNetwork#2]
I'm trying to download the cons_loc_pathway files and it gives the link [https://bbp.epfl.ch/nmc-portal/downloads], but that link just takes me to [https://bbp.epfl.ch/nmc-portal/welcome.html]. I found [https://bbp.epfl.ch/nmc-portal/downloads.html](this) page but it's unclear to me exactly what I have to download.

**Comment by K843Barber** [comment]
Revised location for downloads, explained what to download and where.
